### ISSUE TITLE
Missing crd after build

### ISSUE THREAD

**Issue by aserowy** [arnarg/nixidy#28]
Heho,

i am new in this nix -> gitops process and started using nixidy to build a homelab with cilium. Building the configs cilium couldnt got installed through argo cd because no crd where placed in the build output. (only after manually installing cilium on the cluster fixed it for me). Is this default behavior, is it bugged or am i doing something wrong?

generated crd: https://github.com/aserowy/dots/tree/main/cluster/crd
module: https://github.com/aserowy/dots/blob/main/cluster/homelab/default.nix
cilium: https://github.com/aserowy/dots/blob/main/cluster/homelab/cilium.nix
(code is mainly simplified version of @arnarg cluster integration)

Kind regards
Alexander

**Comment by arnarg** [comment]
Hi @aserowy,

Cilium is a little annoying because the helm chart does not include the CRDs, instead the cilium controller will create them on startup.

The way I bootstrapped my cluster was to manually `kubectl apply` the generated manifests for cilium before I even installed ArgoCD (the Cluster didn't have a CNI so it wouldn't work anyway).

So to answer your question, this is a known (to me) behavior of cilium. Upgrades to cilium work fine through nixidy and ArgoCD.

**Comment by aserowy** [comment]
tyvm taking your time and shed some light on my way :D

**Comment by aserowy** [comment]
one more question :D 

With which flags are you starting your k3s?

PS: ty for your work as well!

**Comment by arnarg** [comment]
You're welcome :)

My k3s server config is here: https://github.com/arnarg/config/blob/main/hosts/terra/configuration.nix#L116
